# Generated by Django 5.0.7 on 2024-11-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('vname', models.CharField(max_length=50)),
                ('vid', models.IntegerField(primary_key=True, serialize=False)),
                ('vaddress', models.CharField(max_length=50)),
            ],
        ),
    ]
